// Generated by gencpp from file wheeled_robot_kinematics/DiffDriveIKResponse.msg
// DO NOT EDIT!


#ifndef WHEELED_ROBOT_KINEMATICS_MESSAGE_DIFFDRIVEIKRESPONSE_H
#define WHEELED_ROBOT_KINEMATICS_MESSAGE_DIFFDRIVEIKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <wheeled_robot_kinematics/DiffDriveAction.h>

namespace wheeled_robot_kinematics
{
template <class ContainerAllocator>
struct DiffDriveIKResponse_
{
  typedef DiffDriveIKResponse_<ContainerAllocator> Type;

  DiffDriveIKResponse_()
    : actions()  {
    }
  DiffDriveIKResponse_(const ContainerAllocator& _alloc)
    : actions(_alloc)  {
    }



   typedef std::vector< ::wheeled_robot_kinematics::DiffDriveAction_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::wheeled_robot_kinematics::DiffDriveAction_<ContainerAllocator> >::other >  _actions_type;
  _actions_type actions;




  typedef boost::shared_ptr< ::wheeled_robot_kinematics::DiffDriveIKResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wheeled_robot_kinematics::DiffDriveIKResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DiffDriveIKResponse_

typedef ::wheeled_robot_kinematics::DiffDriveIKResponse_<std::allocator<void> > DiffDriveIKResponse;

typedef boost::shared_ptr< ::wheeled_robot_kinematics::DiffDriveIKResponse > DiffDriveIKResponsePtr;
typedef boost::shared_ptr< ::wheeled_robot_kinematics::DiffDriveIKResponse const> DiffDriveIKResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wheeled_robot_kinematics::DiffDriveIKResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wheeled_robot_kinematics::DiffDriveIKResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wheeled_robot_kinematics

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'wheeled_robot_kinematics': ['/home/simon/catkin_ws/src/wheeled_robot_kinematics/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wheeled_robot_kinematics::DiffDriveIKResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wheeled_robot_kinematics::DiffDriveIKResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheeled_robot_kinematics::DiffDriveIKResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheeled_robot_kinematics::DiffDriveIKResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheeled_robot_kinematics::DiffDriveIKResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheeled_robot_kinematics::DiffDriveIKResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wheeled_robot_kinematics::DiffDriveIKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "de08eddbcd5ebd6a498691a3aa905e76";
  }

  static const char* value(const ::wheeled_robot_kinematics::DiffDriveIKResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xde08eddbcd5ebd6aULL;
  static const uint64_t static_value2 = 0x498691a3aa905e76ULL;
};

template<class ContainerAllocator>
struct DataType< ::wheeled_robot_kinematics::DiffDriveIKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wheeled_robot_kinematics/DiffDriveIKResponse";
  }

  static const char* value(const ::wheeled_robot_kinematics::DiffDriveIKResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wheeled_robot_kinematics::DiffDriveIKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wheeled_robot_kinematics/DiffDriveAction[] actions\n\
\n\
\n\
\n\
================================================================================\n\
MSG: wheeled_robot_kinematics/DiffDriveAction\n\
float64 left_velocity\n\
float64 right_velocity\n\
float64 time\n\
\n\
";
  }

  static const char* value(const ::wheeled_robot_kinematics::DiffDriveIKResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wheeled_robot_kinematics::DiffDriveIKResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.actions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct DiffDriveIKResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wheeled_robot_kinematics::DiffDriveIKResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wheeled_robot_kinematics::DiffDriveIKResponse_<ContainerAllocator>& v)
  {
    s << indent << "actions[]" << std::endl;
    for (size_t i = 0; i < v.actions.size(); ++i)
    {
      s << indent << "  actions[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::wheeled_robot_kinematics::DiffDriveAction_<ContainerAllocator> >::stream(s, indent + "    ", v.actions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHEELED_ROBOT_KINEMATICS_MESSAGE_DIFFDRIVEIKRESPONSE_H
