// Generated by gencpp from file wheeled_robot_kinematics/DiffDriveIK.msg
// DO NOT EDIT!


#ifndef WHEELED_ROBOT_KINEMATICS_MESSAGE_DIFFDRIVEIK_H
#define WHEELED_ROBOT_KINEMATICS_MESSAGE_DIFFDRIVEIK_H

#include <ros/service_traits.h>


#include <wheeled_robot_kinematics/DiffDriveIKRequest.h>
#include <wheeled_robot_kinematics/DiffDriveIKResponse.h>


namespace wheeled_robot_kinematics
{

struct DiffDriveIK
{

typedef DiffDriveIKRequest Request;
typedef DiffDriveIKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DiffDriveIK
} // namespace wheeled_robot_kinematics


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wheeled_robot_kinematics::DiffDriveIK > {
  static const char* value()
  {
    return "72b62ffb846e210a0b026254440e0b70";
  }

  static const char* value(const ::wheeled_robot_kinematics::DiffDriveIK&) { return value(); }
};

template<>
struct DataType< ::wheeled_robot_kinematics::DiffDriveIK > {
  static const char* value()
  {
    return "wheeled_robot_kinematics/DiffDriveIK";
  }

  static const char* value(const ::wheeled_robot_kinematics::DiffDriveIK&) { return value(); }
};


// service_traits::MD5Sum< ::wheeled_robot_kinematics::DiffDriveIKRequest> should match 
// service_traits::MD5Sum< ::wheeled_robot_kinematics::DiffDriveIK > 
template<>
struct MD5Sum< ::wheeled_robot_kinematics::DiffDriveIKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wheeled_robot_kinematics::DiffDriveIK >::value();
  }
  static const char* value(const ::wheeled_robot_kinematics::DiffDriveIKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wheeled_robot_kinematics::DiffDriveIKRequest> should match 
// service_traits::DataType< ::wheeled_robot_kinematics::DiffDriveIK > 
template<>
struct DataType< ::wheeled_robot_kinematics::DiffDriveIKRequest>
{
  static const char* value()
  {
    return DataType< ::wheeled_robot_kinematics::DiffDriveIK >::value();
  }
  static const char* value(const ::wheeled_robot_kinematics::DiffDriveIKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wheeled_robot_kinematics::DiffDriveIKResponse> should match 
// service_traits::MD5Sum< ::wheeled_robot_kinematics::DiffDriveIK > 
template<>
struct MD5Sum< ::wheeled_robot_kinematics::DiffDriveIKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wheeled_robot_kinematics::DiffDriveIK >::value();
  }
  static const char* value(const ::wheeled_robot_kinematics::DiffDriveIKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wheeled_robot_kinematics::DiffDriveIKResponse> should match 
// service_traits::DataType< ::wheeled_robot_kinematics::DiffDriveIK > 
template<>
struct DataType< ::wheeled_robot_kinematics::DiffDriveIKResponse>
{
  static const char* value()
  {
    return DataType< ::wheeled_robot_kinematics::DiffDriveIK >::value();
  }
  static const char* value(const ::wheeled_robot_kinematics::DiffDriveIKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WHEELED_ROBOT_KINEMATICS_MESSAGE_DIFFDRIVEIK_H
